# Dotfile deployment.
#
# Home-manager module: declares `userSettings.dotfiles.enable` and, when on,
# symlinks the tracked trees under stow/config into ~/.config and stow/home
# into ~/. The links are kept "out of store" (they point
# straight at the repo checkout) so editing a file in the repo takes effect
# immediately, without a home-manager rebuild — which is why the module needs
# to know where that checkout lives (`repoRoot`).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.userSettings.dotfiles;

  configDir = ../../stow/config;
  homeDir = ../../stow/home;
  availableEntries = lib.unique (
    # These entries are generated by dedicated Home Manager modules.
    lib.filter (
      name:
      !(builtins.elem name [
        "tmux"
        "fish"
        "ghostty"
        "opencode"
        "starship.toml"
      ])
    ) (builtins.attrNames (builtins.readDir configDir))
    ++ [ "nvim" ]
  );
  selectedEntries = if cfg.entries == null then availableEntries else cfg.entries;

  filesIn =
    dir:
    lib.concatMap (
      name:
      let
        path = dir + "/${name}";
        type = (builtins.readDir dir).${name};
      in
      if type == "directory" then map (child: "${name}/${child}") (filesIn path) else [ name ]
    ) (builtins.attrNames (builtins.readDir dir));

  # Selected entries under stow/config become matching ~/.config/<name> links.
  configEntries = builtins.listToAttrs (
    map (name: {
      name = ".config/${name}";
      value.source = config.lib.file.mkOutOfStoreSymlink "${cfg.repoRoot}/stow/config/${name}";
    }) selectedEntries
  );

  # Link individual files so stateful directories such as ~/.claude remain
  # writable without placing runtime data in the repository.
  homeEntries = builtins.listToAttrs (
    map (name: {
      inherit name;
      value = {
        source = config.lib.file.mkOutOfStoreSymlink "${cfg.repoRoot}/stow/home/${name}";
        force = name == ".claude/settings.json";
      };
    }) (filesIn homeDir)
  );
in
{
  options.userSettings.dotfiles = {
    enable = lib.mkEnableOption "symlinking the tracked dotfiles into $HOME";

    repoRoot = lib.mkOption {
      type = lib.types.str;
      default = "/home/nomig/projects/personal/.dotfiles";
      description = ''
        Absolute path to this repository's checkout on the target machine.
        Used to build the out-of-store symlinks for ~/.config so edits in the
        repo take effect without a home-manager rebuild.
      '';
    };

    entries = lib.mkOption {
      type = lib.types.nullOr (lib.types.listOf (lib.types.enum availableEntries));
      default = null;
      description = "Dotfile entries to link, or all tracked entries when null.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.file = configEntries // homeEntries;

    # Replace whole-directory links before installing generated config files.
    # Keep runtime state while leaving old Fisher-managed functions behind.
    home.activation.migrateGeneratedConfigDirectories =
      lib.hm.dag.entryBetween [ "linkGeneration" ] [ "writeBoundary" ]
        (
          lib.concatMapStringsSep "\n"
            (name: ''
              configDir=${lib.escapeShellArg "${config.xdg.configHome}/${name}"}
              repoDir=${lib.escapeShellArg "${cfg.repoRoot}/stow/config/${name}"}
              if [[ -L "$configDir" && "$(${pkgs.coreutils}/bin/readlink -m "$configDir")" == "$repoDir" ]]; then
                run unlink "$configDir"
                run mkdir -p "$configDir"
                ${lib.optionalString (name == "fish") ''
                  if [[ -f "$repoDir/fish_variables" ]]; then
                    run ${pkgs.coreutils}/bin/cp -n "$repoDir/fish_variables" "$configDir/fish_variables"
                  fi
                ''}
                ${lib.optionalString (name == "ghostty") ''
                  if [[ -f "$repoDir/themes/dankcolors" ]]; then
                    run mkdir -p "$configDir/themes"
                    run ${pkgs.coreutils}/bin/cp -n "$repoDir/themes/dankcolors" "$configDir/themes/dankcolors"
                  fi
                ''}
                ${lib.optionalString (name == "opencode") ''
                  # Retain local plugins and dependencies from the old directory
                  # link; subsequent activations leave this writable directory alone.
                  run ${pkgs.coreutils}/bin/cp -a -n "$repoDir/." "$configDir/"
                ''}
              fi
            '')
            (
              lib.optional config.userSettings.fish.enable "fish"
              ++ lib.optional config.userSettings.ghostty.enable "ghostty"
              ++ lib.optional config.programs.opencode.enable "opencode"
            )
        );
  };
}
