# wallpaper stuff
exec-once = swww-daemon --format xrgb

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# startup apps
exec-once = nm-applet --indicator
exec-once = mako
exec-once = ags
exec-once = blueman-applet
exec-once = waybar -c ~/.config/waybar/config-main.jsonc
exec-once = waybar -c ~/.config/waybar/config-second.jsonc
exec-once = hyprpaper
exec-once = hyprsunset

exec-once = walker --gapplication-service
exec-once = thunar --daemon
exec-once = elephant
exec-once = openrgb -p Default

# Apps
exec-once = [workspace 1; monitor $monitor1] $terminal
exec-once = [workspace 2; monitor $monitor2] firefox

# Starting windows on a given workspace and monitor silently reliably requires this thing
# Steam workspace 5 silent, monitor 1
windowrule = match:class ^(steam)$, workspace 5 silent, monitor $monitor1
exec-once = steam
exec-once = sleep 30 && hyprctl keyword windowrule "match:class ^(steam)$, workspace unset"

# YouTube Music workspace 3 silent, monitor 2
windowrule = match:class ^(youtube-music)$, workspace 3 silent, monitor $monitor2
exec-once = youtube-music
exec-once = sleep 30 && hyprctl keyword windowrule "match:class ^(youtube-music)$, workspace unset"

# WhatsApp (Chromium app) workspace 3 silent, monitor 2
windowrule = match:title ^(WhatsApp)$, workspace 3 silent, monitor $monitor2
exec-once = chromium --app=https://web.whatsapp.com
exec-once = sleep 30 && hyprctl keyword windowrule "match:title ^(WhatsApp)$, workspace unset"

# ChatGPT (Chromium app) workspace 6 silent, monitor 2
windowrule = match:title ^(ChatGPT)$, workspace 6 silent, monitor $monitor2
exec-once = chromium --app=https://chatgpt.com
exec-once = sleep 30 && hyprctl keyword windowrule "match:title ^(ChatGPT)$, workspace unset"
