format = """\
$python\
$directory\
[](fg:#3D3D3D bg:#42b4ff)\
$git_branch\
$git_metrics\
[](fg:#42b4ff bg:none)\
$character\
"""

# [](bg:#3D3D3D fg:#42b4ff)\
# No new line between shell prompts
add_newline = false

# No line-break between shell prompts
[python]
symbol = '  '
style = "fg:#3D3D3D bg:#42b4ff"
format = '[${symbol}(${version} )(\($virtualenv\) )]($style)[](bg:#3D3D3D fg:#42b4ff)'

pyenv_version_name = true

[line_break]
disabled = true


[directory]
format = "[  $path ]($style)"
style = "fg:#ffffff bg:#3D3D3D"

[git_branch]
format = '[ $symbol$branch]($style)'
symbol = " "
style = "fg:#303446 bg:#42b4ff"

[git_status]
format = '[$all_status]($style)'
style = "fg:#303446 bg:#42b4ff"
ahead = "⇡${count} "
diverged = "⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
modified = "!${count} "
untracked = "?${count} "
staged = "+${count} "

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱎫 $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[ ➜](#a6d189) '
error_symbol = '[ ➜](#E78284) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[ 󱑍 $time ](bg:#666666 fg:#ffffff)]($style)'
