#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/projects -mindepth 2 -maxdepth 2 -type d | fzf \
        --color=fg:-1,fg+:#aac5e6,bg:-1,bg+:-1 \
        --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#87ff00 \
        --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff,header:#87afaf \
        --color=border:#262626,label:#aeaeae,query:#d9d9d9 \
        --preview-window="border-rounded" \
        --prompt="> " \
        --marker=">" \
        --pointer="◆" \
        --separator="" \
        --scrollbar="│" \
        --layout="reverse" \
        --info="right")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
#     tmux new-session -ds $selected_name -c $selected
#     exit 0
# fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected "nvim; exec $SHELL"
    tmux new-window -d -t $selected_name -c $selected
    tmux new-window -d -t $selected_name -c $selected
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
